// This file is auto-generated by xtask. DO NOT EDIT.

export const RUST_PATHS = {
  CONFIG: "/data/adb/meta-hybrid/config.toml",
  MODE_CONFIG: "/data/adb/meta-hybrid/module_mode.conf",
  IMAGE_MNT: "/data/adb/meta-hybrid/img_mnt",
  DAEMON_STATE: "/data/adb/meta-hybrid/run/daemon_state.json",
  DAEMON_LOG: "/data/adb/meta-hybrid/daemon.log",
};

export const BUILTIN_PARTITIONS = ["system", "vendor", "product", "system_ext", "odm", "oem"];